### ISSUE TITLE
Total site Style broken :( 

### ISSUE THREAD

**Issue by ozinteractive** [vinhnglx/active_bootstrap_skin#12]
http://prntscr.com/bx8o4d

**Comment by vinhnglx** [comment]
Please give to me more detail about that: which rails version? which active admin version? which my gem version? ... I tried this gem for many projects, and it's works fine. @ozinteractive

**Comment by saroar** [comment]
thanks everything is work find it was my mistake i didnt remove import files  
@import "active_admin/mixins";
@import "active_admin/base";

**Comment by ozinteractive** [comment]
after remove this file work good

**Comment by vinhnglx** [comment]
thanks man :D hehe @ozinteractive
