### ISSUE TITLE
top menu navbar not becomes droppable

### ISSUE THREAD

**Issue by okliv** [vinhnglx/active_bootstrap_skin#4]
hi! nice work!

i have a trouble with top navigation menu - it simply not collapses to parent categories. all child links are just placed under the parent one...

**Comment by vinhnglx** [comment]
@okliv yes, I agree with you. This issue needs a help. Could you contribute for this issue?

**Comment by jasper502** [comment]
same issue here

**Comment by mrosso10** [comment]
@vinhnglx Hi, I'm working on a fix for this issue. Can I push a new branch and a PR?

**Comment by mrosso10** [comment]
Oh, I was trying to push to this repo. Didn't know that I need to fork and then submit the PR. :grin:

**Comment by vinhnglx** [comment]
@okliv @mrosso10 @jasper502  I've just created new PR ( #8 ) for this issue

**Comment by vinhnglx** [comment]
merged and release new version. I'll close this issue
